/**
 * GitHub Copilot Cloud Agent Support
 *
 * Generates copilot-setup-steps.yml and .github/agents/codespec.agent.md
 * when the github-copilot tool is selected during init/update.
 * These files enable the GitHub Copilot coding agent (cloud) to use the
 * CodeSpec CLI in its ephemeral dev environment.
 */

import path from 'path';
import { promises as fs } from 'fs';
import { Document, YAMLMap, parseDocument, isMap } from 'yaml';
import { FileSystemUtils } from '../../utils/file-system.js';
import { readProjectConfig, resolveConfigFilePath } from '../project-config.js';

const COPILOT_TOOL_ID = 'github-copilot';
const CODESPEC_MANAGED_MARKER = 'Generated by CodeSpec for GitHub Copilot coding agent support.';

/**
 * Check if a tool list includes github-copilot.
 */
export function includesGitHubCopilot(toolIds: string[]): boolean {
  return toolIds.includes(COPILOT_TOOL_ID);
}

/**
 * Generate the copilot-setup-steps.yml workflow file content.
 * This workflow pre-installs the CodeSpec CLI in the Copilot coding agent's
 * ephemeral GitHub Actions environment.
 */
export function generateCopilotSetupSteps(): string {
  return `# ${CODESPEC_MANAGED_MARKER}

${generateCopilotSetupStepsBody()}`;
}

function generateCopilotSetupStepsBody(): string {
  return `name: "Copilot Setup Steps"

# Runs automatically when changed (for validation) and can be triggered manually.
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called \`copilot-setup-steps\` for Copilot coding agent to pick it up.
  copilot-setup-steps:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CodeSpec CLI
        run: npm install -g @hrhy-ai/codespec

      - name: Verify CodeSpec CLI
        run: codespec --version
`;
}

/**
 * Generate the .github/agents/codespec.agent.md custom agent file content.
 * This tells the GitHub Copilot coding agent how to use the CodeSpec CLI.
 */
export function generateCopilotAgentFile(): string {
  return generateCopilotAgentFileBody(true);
}

function generateCopilotAgentFileBody(includeManagedMarker = false): string {
  const managedMarker = includeManagedMarker
    ? `<!-- ${CODESPEC_MANAGED_MARKER} -->\n\n`
    : '';

  return `---
name: CodeSpec
description: "Manages CodeSpec changes, specs, and workflows using the CodeSpec CLI. Use this agent for proposing changes, exploring ideas, validating artifacts, checking status, and archiving completed work."
tools:
  - "execute"
  - "read"
  - "search"
  - "edit"
---

${managedMarker}# CodeSpec Agent

You are a specialized agent for managing CodeSpec workflows. Before using the \`codespec\` CLI, run \`codespec --version\`. If it is unavailable, install it with \`npm install -g @hrhy-ai/codespec\`.

## What is CodeSpec?

CodeSpec is a structured change management system for codebases. It organizes work into **changes** with planning artifacts (proposals, specs, designs, tasks) that guide implementation.

## Available Commands

### Agent-Compatible CLI Commands (prefer \`--json\` for structured output)

| Command | Purpose |
|---------|---------|
| \`codespec list [--json]\` | List all changes and specs |
| \`codespec show <item> [--json]\` | View a specific change or spec |
| \`codespec validate [--all] [--json]\` | Validate changes and specs for issues |
| \`codespec status [--change <name>] [--json]\` | Show artifact progress for a change |
| \`codespec instructions [artifact] [--change <name>] [--json]\` | Get next-step instructions for a change |
| \`codespec templates [--json]\` | List available templates |
| \`codespec schemas [--json]\` | List available workflow schemas |
| \`codespec archive <change>\` | Archive a completed change after interactive human confirmation; JSON and automation are not supported |

### Interactive CLI Commands (use when prompted by the user)

| Command | Purpose |
|---------|---------|
| \`codespec init\` | Initialize CodeSpec in the project |
| \`codespec update\` | Update CodeSpec configuration and artifacts |
| \`codespec view\` | Interactive dashboard |
| \`codespec config\` | View or modify settings |

## Workflow

When asked to work with CodeSpec, follow this pattern:

1. **Find the change**: Run \`codespec list --json\` to see active changes.
2. **Check progress**: Run \`codespec status --change <name> --json\` for the selected change.
3. **Follow instructions**: Run \`codespec instructions [artifact] --change <name> --json\` for the next artifact.
4. **Validate before completing**: Run \`codespec validate <name> --json\`.

## Creating New Changes

When the user wants to propose a new change:

1. Run \`codespec new change <name>\`.
2. Run \`codespec status --change <name> --json\` to see the artifact sequence.
3. Use \`codespec instructions [artifact] --change <name> --json\` before creating each artifact.
4. Run \`codespec validate <name> --json\` when the artifacts are complete.

## Key Directories

- \`codespec/\` — Root CodeSpec directory
- \`codespec/changes/\` — Active changes with their artifacts
- \`codespec/config.yaml\` — Project configuration

## Best Practices

- Always use \`--json\` flag when you need to parse output programmatically
- Run \`codespec validate\` after creating or modifying artifacts
- Check \`codespec status\` before starting work to understand the current state
- When archiving, ensure all tasks are completed and validated first
`;
}

function generatePreviousCopilotAgentFileBody(includeManagedMarker = false): string {
  let content = generateCopilotAgentFileBody();
  content = replaceRequired(
    content,
    'You are a specialized agent for managing CodeSpec workflows. Before using the `codespec` CLI, run `codespec --version`. If it is unavailable, install it with `npm install -g @hrhy-ai/codespec`.',
    'You are a specialized agent for managing CodeSpec workflows. You have access to the `codespec` CLI through shell commands, pre-installed in the development environment via `copilot-setup-steps.yml`.',
    'previous CLI access sentence'
  );
  content = replaceRequired(
    content,
    '| `codespec archive <change>` | Archive a completed change after interactive human confirmation; JSON and automation are not supported |',
    '| `codespec archive <change>` | Archive a completed change |',
    'previous archive command row'
  );

  if (!includeManagedMarker) {
    return content;
  }

  return replaceRequired(
    content,
    '\n# CodeSpec Agent',
    `\n<!-- ${CODESPEC_MANAGED_MARKER} -->\n\n# CodeSpec Agent`,
    'previous agent heading'
  );
}

function generateLegacyCopilotAgentFileBody(): string {
  let content = generatePreviousCopilotAgentFileBody();
  content = replaceRequired(
    content,
    `## Workflow

When asked to work with CodeSpec, follow this pattern:

1. **Find the change**: Run \`codespec list --json\` to see active changes.
2. **Check progress**: Run \`codespec status --change <name> --json\` for the selected change.
3. **Follow instructions**: Run \`codespec instructions [artifact] --change <name> --json\` for the next artifact.
4. **Validate before completing**: Run \`codespec validate <name> --json\`.

## Creating New Changes

When the user wants to propose a new change:

1. Run \`codespec new change <name>\`.
2. Run \`codespec status --change <name> --json\` to see the artifact sequence.
3. Use \`codespec instructions [artifact] --change <name> --json\` before creating each artifact.
4. Run \`codespec validate <name> --json\` when the artifacts are complete.`,
    `## Workflow

When asked to work with CodeSpec, follow this pattern:

1. **Check current state**: Run \`codespec status --json\` to understand what changes exist and their progress.
2. **Follow instructions**: Run \`codespec instructions --json\` to get context-aware next steps.
3. **Validate before completing**: Run \`codespec validate --all --json\` to ensure artifacts are correct.

## Creating New Changes

When the user wants to propose a new change:

1. Create the change directory under \`codespec/changes/<change-name>/\`
2. Generate the required planning artifacts based on the project's configured workflow schema
3. Run \`codespec validate --json\` to verify the artifacts are well-formed`,
    'legacy workflow guidance'
  );
  content = replaceRequired(
    content,
    `tools:
  - "execute"
  - "read"
  - "search"
  - "edit"`,
    `tools:
  - "terminal"`,
    'legacy tool alias'
  );
  content = replaceRequired(
    content,
    'You are a specialized agent for managing CodeSpec workflows. You have access to the `codespec` CLI through shell commands, pre-installed in the development environment via `copilot-setup-steps.yml`.',
    'You are a specialized agent for managing CodeSpec workflows. You have access to the `codespec` CLI which is pre-installed in the development environment via `copilot-setup-steps.yml`.',
    'legacy CLI access sentence'
  );
  content = replaceRequired(
    content,
    '| `codespec status [--change <name>] [--json]` | Show artifact progress for a change |',
    '| `codespec status [--json]` | Show artifact progress for active changes |',
    'legacy status command row'
  );
  content = replaceRequired(
    content,
    '| `codespec instructions [artifact] [--change <name>] [--json]` | Get next-step instructions for a change |',
    '| `codespec instructions [--json]` | Get next-step instructions for a change |',
    'legacy instructions command row'
  );
  return replaceRequired(
    content,
    '- `codespec/config.yaml` — Project configuration',
    `- \`codespec/config.yaml\` — Project configuration
- \`codespec/explorations/\` — Exploration documents`,
    'legacy exploration directory'
  );
}

function replaceRequired(
  content: string,
  searchValue: string,
  replaceValue: string,
  label: string
): string {
  if (!content.includes(searchValue)) {
    throw new Error(`Cannot build Copilot cloud file content: missing ${label}`);
  }
  return content.replace(searchValue, replaceValue);
}

/**
 * File paths (relative to project root) for the generated files.
 */
export const COPILOT_CLOUD_FILES = {
  setupSteps: path.join('.github', 'workflows', 'copilot-setup-steps.yml'),
  agent: path.join('.github', 'agents', 'codespec.agent.md'),
} as const;

const COPILOT_AGENT_ALTERNATE_FILE = path.join('.github', 'agents', 'codespec.md');

type CopilotCloudFile = (typeof COPILOT_CLOUD_FILES)[keyof typeof COPILOT_CLOUD_FILES];

const COPILOT_CLOUD_FILE_CONTENTS: Record<CopilotCloudFile, string> = {
  [COPILOT_CLOUD_FILES.setupSteps]: generateCopilotSetupSteps(),
  [COPILOT_CLOUD_FILES.agent]: generateCopilotAgentFile(),
};

function getLegacyCopilotCloudFileContents(relPath: CopilotCloudFile): string[] {
  if (relPath === COPILOT_CLOUD_FILES.setupSteps) {
    return [generateCopilotSetupStepsBody()];
  }

  return [
    generateCopilotAgentFileBody(),
    generatePreviousCopilotAgentFileBody(),
    generatePreviousCopilotAgentFileBody(true),
    generateLegacyCopilotAgentFileBody(),
  ];
}

function normalizeLineEndings(content: string): string {
  return content.replace(/\r\n/g, '\n');
}

function isCurrentCopilotCloudFile(
  relPath: CopilotCloudFile,
  content: string
): boolean {
  return normalizeLineEndings(content) === COPILOT_CLOUD_FILE_CONTENTS[relPath];
}

function isLegacyCopilotCloudFile(
  relPath: CopilotCloudFile,
  content: string
): boolean {
  return getLegacyCopilotCloudFileContents(relPath).includes(normalizeLineEndings(content));
}

function isManagedCopilotCloudFile(
  relPath: CopilotCloudFile,
  content: string
): boolean {
  return isCurrentCopilotCloudFile(relPath, content) || isLegacyCopilotCloudFile(relPath, content);
}

async function reconcileCopilotCloudFile(
  fullPath: string,
  relPath: CopilotCloudFile
): Promise<boolean> {
  const currentContent = COPILOT_CLOUD_FILE_CONTENTS[relPath];

  if (!(await FileSystemUtils.fileExists(fullPath))) {
    await FileSystemUtils.writeFile(fullPath, currentContent);
    return true;
  }

  const existingContent = await FileSystemUtils.readFile(fullPath);
  if (isCurrentCopilotCloudFile(relPath, existingContent)) {
    return false;
  }
  if (!isLegacyCopilotCloudFile(relPath, existingContent)) {
    return false;
  }

  await FileSystemUtils.writeFile(fullPath, currentContent);
  return true;
}

async function assertCreatableFilePath(filePath: string): Promise<void> {
  let candidate = path.dirname(filePath);

  while (true) {
    try {
      const stats = await fs.stat(candidate);
      if (!stats.isDirectory()) {
        throw new Error(`Parent path is not a directory: ${candidate}`);
      }
      return;
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
        throw error;
      }
    }

    const parent = path.dirname(candidate);
    if (parent === candidate) {
      throw new Error(`Cannot resolve a directory ancestor for: ${filePath}`);
    }
    candidate = parent;
  }
}

async function assertMissingOrRegularFile(filePath: string): Promise<void> {
  try {
    const stats = await fs.stat(filePath);
    if (!stats.isFile()) {
      throw new Error(`Managed Copilot path is not a regular file: ${filePath}`);
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      throw error;
    }
  }
}

async function classifyCopilotAgentReconciliation(
  agentPath: string,
  alternateAgentPath: string
): Promise<'reconcile' | 'skip' | 'remove-managed'> {
  if (!(await FileSystemUtils.fileExists(alternateAgentPath))) {
    return 'reconcile';
  }
  if (!(await FileSystemUtils.fileExists(agentPath))) {
    return 'skip';
  }

  const existingContent = await FileSystemUtils.readFile(agentPath);
  if (isManagedCopilotCloudFile(COPILOT_CLOUD_FILES.agent, existingContent)) {
    return 'remove-managed';
  }

  throw new Error(
    `Conflicting Copilot agent profiles: preserve either ${COPILOT_AGENT_ALTERNATE_FILE} or ${COPILOT_CLOUD_FILES.agent}`
  );
}

/**
 * Reconcile Copilot cloud agent files in the project directory.
 * Creates missing files and refreshes recognized legacy generated files while
 * preserving current generated content and user customizations.
 *
 * @returns Object indicating which files were written.
 */
export async function writeCopilotCloudFiles(
  projectPath: string
): Promise<{ setupStepsWritten: boolean; agentWritten: boolean }> {
  const setupStepsPath = FileSystemUtils.resolveProjectArtifactPath(
    projectPath,
    COPILOT_CLOUD_FILES.setupSteps
  );
  const agentPath = FileSystemUtils.resolveProjectArtifactPath(
    projectPath,
    COPILOT_CLOUD_FILES.agent
  );
  const alternateAgentPath = FileSystemUtils.resolveProjectArtifactPath(
    projectPath,
    COPILOT_AGENT_ALTERNATE_FILE
  );

  await assertCreatableFilePath(setupStepsPath);
  await assertCreatableFilePath(agentPath);
  await assertMissingOrRegularFile(setupStepsPath);
  await assertMissingOrRegularFile(agentPath);
  await assertMissingOrRegularFile(alternateAgentPath);
  const agentReconciliation = await classifyCopilotAgentReconciliation(
    agentPath,
    alternateAgentPath
  );

  const setupStepsWritten = await reconcileCopilotCloudFile(
    setupStepsPath,
    COPILOT_CLOUD_FILES.setupSteps
  );
  let agentWritten = false;
  if (agentReconciliation === 'reconcile') {
    agentWritten = await reconcileCopilotCloudFile(agentPath, COPILOT_CLOUD_FILES.agent);
  } else if (agentReconciliation === 'remove-managed') {
    await fs.unlink(agentPath);
  }

  return { setupStepsWritten, agentWritten };
}

/**
 * Remove copilot cloud agent files from the project directory.
 * Used when github-copilot is deselected.
 *
 * @returns Number of files removed.
 */
export async function removeCopilotCloudFiles(projectPath: string): Promise<number> {
  let removed = 0;
  const managedPaths = Object.values(COPILOT_CLOUD_FILES).map((relPath) => ({
    relPath,
    fullPath: FileSystemUtils.resolveProjectArtifactPath(projectPath, relPath),
  }));
  for (const { fullPath } of managedPaths) {
    await assertMissingOrRegularFile(fullPath);
  }

  for (const { relPath, fullPath } of managedPaths) {
    if (await FileSystemUtils.fileExists(fullPath)) {
      const content = await FileSystemUtils.readFile(fullPath);
      if (!isManagedCopilotCloudFile(relPath, content)) {
        continue;
      }

      await fs.unlink(fullPath);
      removed++;
    }
  }

  return removed;
}

// ─────────────────────────────────────────────────────────────────────────────
// Opt-in
//
// Generating a GitHub Actions workflow into a user's `.github/` is invasive and
// ties us to Copilot's externally-owned coding-agent format, so cloud files are
// opt-in rather than an automatic side effect of selecting the Copilot tool.
// The decision is persisted in codespec/config.yaml so non-interactive
// `codespec update` (CI, agents) honors it without ever prompting.
// ─────────────────────────────────────────────────────────────────────────────

const COPILOT_CONFIG_KEY = 'githubCopilot';
const COPILOT_CLOUD_AGENT_KEY = 'cloudAgent';

/**
 * Read the persisted opt-in for Copilot cloud-file generation.
 *
 * Tri-state: `true` (opted in), `false` (explicitly opted out), or `undefined`
 * (never decided). A malformed value is treated as undecided rather than an
 * error, matching how {@link readProjectConfig} degrades on bad fields.
 */
export function readCopilotCloudOptIn(projectPath: string): boolean | undefined {
  const value = readProjectConfig(projectPath)?.githubCopilot?.cloudAgent;
  return typeof value === 'boolean' ? value : undefined;
}

/**
 * True when a managed Copilot cloud file (the current generation or a
 * recognized legacy one) already exists. Projects created before the opt-in
 * prompt existed are treated as implicitly opted in, so `codespec update`
 * keeps their files current instead of silently abandoning them.
 */
export async function hasExistingManagedCloudFiles(projectPath: string): Promise<boolean> {
  for (const relPath of Object.values(COPILOT_CLOUD_FILES)) {
    const fullPath = FileSystemUtils.resolveProjectArtifactPath(projectPath, relPath);
    if (!(await FileSystemUtils.fileExists(fullPath))) {
      continue;
    }
    const content = await FileSystemUtils.readFile(fullPath);
    if (isManagedCopilotCloudFile(relPath, content)) {
      return true;
    }
  }
  return false;
}

/**
 * Effective decision on whether to generate/refresh Copilot cloud files.
 * An explicit opt-in or opt-out always wins; when undecided, fall back to
 * whether managed files already exist (the migration path above).
 */
export async function isCopilotCloudEnabled(projectPath: string): Promise<boolean> {
  const optIn = readCopilotCloudOptIn(projectPath);
  if (typeof optIn === 'boolean') {
    return optIn;
  }
  return hasExistingManagedCloudFiles(projectPath);
}

/**
 * Persist the Copilot cloud opt-in into codespec/config.yaml.
 *
 * Uses the YAML document model rather than a re-serialize so the user's
 * existing comments, ordering, and formatting survive untouched — the config
 * file is hand-authored and heavily commented, so a lossy round-trip would be
 * its own source of toil. No-op when no config file exists yet (init creates it
 * before this is called); the caller treats persistence failures as non-fatal.
 */
export async function persistCopilotCloudOptIn(
  projectPath: string,
  value: boolean
): Promise<void> {
  const configPath = resolveConfigFilePath(projectPath);
  if (!configPath) {
    return;
  }
  const existing = await FileSystemUtils.readFile(configPath);
  const parsed = parseDocument(existing);
  // A file YAML can't parse cleanly — a multi-document stream, a tab-indented
  // syntax error — can't be edited without corrupting it, and toString() would
  // throw. Leave it untouched rather than clobber or crash; such a file is
  // already invalid, so readProjectConfig ignores it anyway.
  if (parsed.errors.length > 0) {
    return;
  }
  // `setIn(['githubCopilot', ...])` needs a top-level map. A config whose root
  // is anything else — a scalar (`null`, a bare string) or even a sequence —
  // has no map to set a key on and makes setIn throw. Such a file is already
  // invalid (readProjectConfig rejects it), so start fresh rather than crash.
  // An empty or comment-only file parses to null contents, which setIn fills in
  // while keeping the comments — so only a non-map root is discarded.
  const doc: Document =
    parsed.contents === null || isMap(parsed.contents) ? parsed : new Document();
  // The root is a map now, but the `githubCopilot` node itself may be a stray
  // scalar/sequence/null (e.g. `githubCopilot: false`) — descending into that
  // with setIn also throws. Replace any non-map node with an empty map first.
  const section = doc.getIn([COPILOT_CONFIG_KEY], true);
  if (section !== undefined && !isMap(section)) {
    doc.setIn([COPILOT_CONFIG_KEY], new YAMLMap());
  }
  doc.setIn([COPILOT_CONFIG_KEY, COPILOT_CLOUD_AGENT_KEY], value);
  await FileSystemUtils.writeFile(configPath, doc.toString());
}

/**
 * Return the managed cloud-file paths (relative to the project root) that
 * currently hold user-owned, non-managed content — i.e. files CodeSpec will
 * deliberately leave untouched. Used to tell an opted-in user that we preserved
 * their existing file rather than silently doing nothing, which is the honest
 * answer to "will this affect my existing Copilot cloud setup?".
 */
export async function findUnmanagedCloudFiles(projectPath: string): Promise<string[]> {
  const collisions: string[] = [];
  for (const relPath of Object.values(COPILOT_CLOUD_FILES)) {
    const fullPath = FileSystemUtils.resolveProjectArtifactPath(projectPath, relPath);
    if (!(await FileSystemUtils.fileExists(fullPath))) {
      continue;
    }
    const content = await FileSystemUtils.readFile(fullPath);
    if (!isManagedCopilotCloudFile(relPath, content)) {
      collisions.push(relPath);
    }
  }
  return collisions;
}

/**
 * Return the managed cloud-file paths (relative to the project root) that
 * currently exist and hold CodeSpec-generated content. Callers report this
 * rather than the intended paths, so output never claims a file that a write
 * skipped (user already owns it) or that reconciliation removed.
 */
export async function listManagedCloudFiles(projectPath: string): Promise<string[]> {
  const present: string[] = [];
  for (const relPath of Object.values(COPILOT_CLOUD_FILES)) {
    const fullPath = FileSystemUtils.resolveProjectArtifactPath(projectPath, relPath);
    if (!(await FileSystemUtils.fileExists(fullPath))) {
      continue;
    }
    const content = await FileSystemUtils.readFile(fullPath);
    if (isManagedCopilotCloudFile(relPath, content)) {
      present.push(relPath);
    }
  }
  return present;
}
